/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Enable ninfod syslog messages. */
#define ENABLE_DEBUG 1

/* If set enable I18N. */
#define ENABLE_NLS 1

/* Defined if libpthread is found. */
#define ENABLE_THREADS 1

/* Define if error.h can be included. */
#define HAVE_ERROR_H 1

/* Define if inttypes.h can be included. */
#define HAVE_INTTYPES_H 1

/* Defined if libcap exists. */
#define HAVE_LIBCAP 1

/* Define if limits.h can be included. */
#define HAVE_LIMITS_H 1

/* Define if linux/rtnetlink.h can be included. */
#define HAVE_LINUX_RTNETLINK_H 1

/* Define if memory.h can be included. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the nanosleep function */
#define HAVE_NANOSLEEP 1

/* Define if netdb.h can be included. */
#define HAVE_NETDB_H 1

/* Define if netinet/icmp6.h can be included. */
#define HAVE_NETINET_ICMP6_H 1

/* Define if netinet/in.h can be included. */
#define HAVE_NETINET_IN_H 1

/* Define if netinet/ip6.h can be included. */
#define HAVE_NETINET_IP6_H 1

/* Define if pwd.h can be included. */
#define HAVE_PWD_H 1

/* Define if stdint.h can be included. */
#define HAVE_STDINT_H 1

/* Define if stdlib.h can be included. */
#define HAVE_STDLIB_H 1

/* Define if strings.h can be included. */
#define HAVE_STRINGS_H 1

/* Define if string.h can be included. */
#define HAVE_STRING_H 1

/* Define if syslog.h can be included. */
#define HAVE_SYSLOG_H 1

/* Define if sys/capability.h can be included. */
#define HAVE_SYS_CAPABILITY_H 1

/* Define if sys/time.h can be included. */
#define HAVE_SYS_TIME_H 1

/* Define if sys/types.h can be included. */
#define HAVE_SYS_TYPES_H 1

/* Define if sys/uio.h can be included. */
#define HAVE_SYS_UIO_H 1

/* Define if sys/utsname.h can be included. */
#define HAVE_SYS_UTSNAME_H 1

/* Define if unistd.h can be included. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the __fpending function */
#define HAVE___FPENDING 1

#define LOCALEDIR "/usr/local/share/locale"

#define PACKAGE_NAME "iputils"

/* If set build rdisc server. */
#define RDISC_SERVER 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Defined if struct tm exists. */
#define TIME_WITH_SYS_TIME 1

/* Enable GNU extensions on systems that have them. */
#define _GNU_SOURCE 1

